#!/usr/bin/env python3
"""Run three independent tool baselines on the pinned marimo case and control.

Workflow definitions are analyzed as files; they are never run. The control is
generated by evaluate_approval_race.py and differs by one comparison operator.
"""
import argparse
from collections import Counter
import json
from pathlib import Path
import shutil
import subprocess
import tempfile
import evaluate_public_cases


QUERY_PACK = 'codeql/actions-queries@0.6.36'
SUITES = {'default': 'actions-code-scanning.qls',
          'security-and-quality': 'actions-security-and-quality.qls'}
PERSONAS = ['regular', 'auditor', 'pedantic']


def run(command, cwd=None):
    return subprocess.run(command, cwd=cwd, capture_output=True, text=True, check=True)


def sarif_stats(file):
    results = json.loads(file.read_text())['runs'][0].get('results', [])
    target = [r for r in results if any('marimo-bot.yml' in
              str(location.get('physicalLocation', {}).get('artifactLocation', {}).get('uri', ''))
              for location in r.get('locations', []))]
    return {'total': len(results), 'targetWorkflow': len(target),
            'rules': dict(sorted(Counter(r['ruleId'] for r in results).items())),
            'targetRules': dict(sorted(Counter(r['ruleId'] for r in target).items()))}


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--case', type=Path, required=True)
    p.add_argument('--control', type=Path, required=True)
    p.add_argument('--codeql', type=Path, required=True)
    p.add_argument('--zizmor', type=Path, required=True)
    p.add_argument('--actionlint', type=Path, required=True)
    p.add_argument('--diagnostic', type=Path, required=True)
    p.add_argument('--output', type=Path, required=True)
    args = p.parse_args()
    if args.output.exists():
        raise FileExistsError('Output directory must be new')
    evaluate_public_cases.verify_manifest(args.case)
    original_files = {p.relative_to(args.case / 'vulnerable'): p
                      for p in (args.case / 'vulnerable').rglob('*') if p.is_file()}
    control_files = {p.relative_to(args.control): p
                     for p in args.control.rglob('*') if p.is_file()}
    if original_files.keys() != control_files.keys():
        raise ValueError('Control has a different file set')
    differences = [str(path) for path in original_files
                   if original_files[path].read_bytes() != control_files[path].read_bytes()]
    if differences != ['.github/workflows/marimo-bot.yml']:
        raise ValueError(f'Expected only the timestamp guard to differ: {differences}')
    before = original_files[Path(differences[0])].read_text()
    after = control_files[Path(differences[0])].read_text()
    if (
        before.count(' -gt $(date -d "$COMMENT_AT" +%s)') != 1
        or after != before.replace(' -gt $(date -d "$COMMENT_AT" +%s)',
                                   ' -ge $(date -d "$COMMENT_AT" +%s)')
    ):
        raise ValueError('Unexpected control edit')
    version = json.loads(run([str(args.codeql), 'version', '--format=json']).stdout)['version']
    if version != evaluate_public_cases.CLI_VERSION:
        raise ValueError(f'Expected CodeQL {evaluate_public_cases.CLI_VERSION}, got {version}')
    run([str(args.codeql), 'pack', 'install', str(args.diagnostic.parent)])
    run([str(args.codeql), 'pack', 'download', QUERY_PACK])
    args.output.mkdir(parents=True)
    report = {'codeql': version, 'queryPack': QUERY_PACK,
              'zizmor': run([str(args.zizmor), '--version']).stdout.strip(),
              'actionlint': run([str(args.actionlint), '-version']).stdout.splitlines()[0],
              'controlDifference': differences, 'variants': {}}
    for label, source in [('vulnerable', args.case / 'vulnerable'),
                          ('reject-equality-control', args.control),
                          ('removed', args.case / 'removed')]:
        dest = args.output / label
        dest.mkdir()
        db = dest / 'database'
        run([str(args.codeql), 'database', 'create', str(db), '--language=actions',
             '--source-root=' + str(source)])
        stats = {'codeql': {}, 'zizmor': {}}
        for suite, filename in SUITES.items():
            sarif = dest / (suite + '.sarif')
            run([str(args.codeql), 'database', 'analyze', str(db),
                 QUERY_PACK + ':codeql-suites/' + filename,
                 '--format=sarif-latest', '--output=' + str(sarif)])
            stats['codeql'][suite] = sarif_stats(sarif)
        if label != 'removed':
            bqrs = dest / 'classification.bqrs'
            csv = dest / 'classification.csv'
            run([str(args.codeql), 'query', 'run', str(args.diagnostic),
                 '--database=' + str(db), '--output=' + str(bqrs)])
            run([str(args.codeql), 'bqrs', 'decode', str(bqrs),
                 '--format=csv', '--output=' + str(csv)])
        for persona in PERSONAS:
            result = run([str(args.zizmor), '--offline', '--no-config', '--no-ignores',
                          '--no-progress', '--no-exit-codes', '--persona=' + persona,
                          '--format=sarif', str(source)])
            sarif = dest / ('zizmor-' + persona + '.sarif')
            sarif.write_text(result.stdout)
            stats['zizmor'][persona] = sarif_stats(sarif)
        # actionlint discovers its project root from Git, so isolate copied
        # bytes from the enclosing research repository before running it.
        with tempfile.TemporaryDirectory() as temp:
            isolated = Path(temp) / 'source'
            shutil.copytree(source, isolated)
            (isolated / '.git').mkdir()
            workflows = [str(x.relative_to(isolated)) for x in
                         sorted((isolated / '.github/workflows').glob('*.yml'))]
            workflows += [str(x.relative_to(isolated)) for x in
                          sorted((isolated / '.github/workflows').glob('*.yaml'))]
            actionlint = subprocess.run(
                [str(args.actionlint), '-shellcheck=', '-pyflakes=',
                 '-format', '{{json .}}', *workflows], cwd=isolated,
                capture_output=True, text=True)
        if actionlint.returncode not in [0, 1]:
            raise RuntimeError(actionlint.stderr)
        (dest / 'actionlint.json').write_text(actionlint.stdout)
        stats['actionlint'] = len(json.loads(actionlint.stdout))
        report['variants'][label] = stats
    (args.output / 'summary.json').write_text(json.dumps(report, ensure_ascii=False, indent=2) + '\n')


if __name__ == '__main__':
    main()
